- name: Expense Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable Nodejs Default Version
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: Enable Nodejs 18 Version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: Install Nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: Copy Backend Service File
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add Application user
      ansible.builtin.user:
        name: expense
    - name: Delete old app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download nd Extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes
    - name: Download Nodejs Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name:  Install mysql Client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-w.decops76s.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes
