- name: Expense Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: Copy Expense Config file
      ansible.builtin.copy:
        src: expense.conf
        destination: /etc/nginx/default.d/expense.conf
    - name: Clean Old Nginx Dir
      ansible.builtin.file
        path: /usr/share/nginx/html
        state: absent
    - name: Create Nginx Dir
      ansible.builtin.file:
        path: /user/share/nginx/html
        state: directory
    - name: Download and Extract Frontend Content
      ansible.builtin.un archive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        destination: /usr/share/nginx/html
        remote_src: yes
    - name: Start nginx Service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
