- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Expense Config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: Start nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import Elk Role - Filebeat
  ansible.builtin.import_role:
    name: Elk
    tasks_from: filebeat

