- name: Copy Elastic YUM Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Import ELK Role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat